export { EventsFormsIndex as General } from './General'
export { EventsFormsRegistration as Registration } from './Registration'
export { EventsFormsOptional as Optional } from './Optional'
export { EventsFormsDetails as Details } from './Details'
export { EventsFormsActions as Actions } from './actions/Actions'