export const campusList = [
    { key: 'MTY', text: 'Campus Monterrey' },
    { key: 'CDMX', text: 'Campus Ciudad de México' },
    { key: 'AGS', text: 'Campus Aguascalientes' },
    { key: 'CS', text: 'Campus Chiapas' },
    { key: 'CH', text: 'Campus Chihuahua' },
    { key: 'CDJZ', text: 'Campus Ciudad Juarez' },
    { key: 'CDOB', text: 'Campus Ciudad Obregón' },
    { key: 'CV', text: 'Campus Cuernavaca' },
    { key: 'EDMX', text: 'Campus Estado de México' },
    { key: 'GDL', text: 'Campus Guadalajara' },
    { key: 'HDL', text: 'Campus Hidalgo' },
    { key: 'IRP', text: 'Campus Irapuato' },
    { key: 'LGN', text: 'Campus Laguna' },
    { key: 'LN', text: 'Campus León' },
    { key: 'MOR', text: 'Campus Morelia' },
    { key: 'PL', text: 'Campus Puebla' },
    { key: 'QRO', text: 'Campus Querétaro' },
    { key: 'SLT', text: 'Campus Saltillo' },
    { key: 'SLP', text: 'Campus San Luis Potosí' },
    { key: 'SF', text: 'Campus Santa Fe' },
    { key: 'SNL', text: 'Campus Sinaloa' },
    { key: 'SNTE', text: 'Campus Sonora Norte' },
    { key: 'TMP', text: 'Campus Tampico' },
    { key: 'TOL', text: 'Campus Toluca' },
    { key: 'ZAC', text: 'Campus Zacatecas' }]

export const users = [
    {
        "id": 2,
        "email": "mail@mail.com",
        "firstName": null,
        "lastName": null,
        "office": null,
        "phoneNumber": null,
        "campus": null,
        "userType": "sponsor",
        "isNewbie": true,
        "disabled": false
    },
    {
        "id": 6,
        "email": "sponsor@mail.com",
        "firstName": null,
        "lastName": null,
        "office": null,
        "phoneNumber": null,
        "campus": null,
        "userType": "sponsor",
        "isNewbie": true,
        "disabled": false
    },
    {
        "id": 7,
        "email": "test@mail.com",
        "firstName": null,
        "lastName": null,
        "office": null,
        "phoneNumber": null,
        "campus": null,
        "userType": "sponsor",
        "isNewbie": true,
        "disabled": false
    },
    {
        "id": 8,
        "email": "pato@mail.com",
        "firstName": null,
        "lastName": null,
        "office": null,
        "phoneNumber": null,
        "campus": null,
        "userType": "admin",
        "isNewbie": true,
        "disabled": true
    },
    {
        "id": 1,
        "email": "a@a.com",
        "firstName": "Abraham",
        "lastName": "Rodriguez",
        "office": "A3-101",
        "phoneNumber": "55-55-55-55",
        "campus": "MTY",
        "userType": "admin",
        "isNewbie": false,
        "disabled": false
    }
]